### ISSUE TITLE
Alternative: flydrive

### ISSUE THREAD

**Issue by targos** [mylims/filesystem#1]
Please have a look at https://github.com/Slynova-Org/flydrive

I'm co-maintainer of the project. It allows to handle files in a storage-agnostic way and supports local file system, Amazon S3 and Google Cloud Storage by default.

**Comment by maasencioh** [comment]
@lpatiny  pointed out, I was thinking how to implement a [signed URL upload](https://www.apollographql.com/blog/apollo-server-file-upload-best-practices-1e7f24cdc050) server

**Comment by maasencioh** [comment]
implemented in #2
